name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install package & dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -e .
          pip install ruff pytest

      - name: Lint with ruff
        run: |
          # lint the codebase (no autofix)
          python -m ruff check .

      - name: Run tests (pytest)
        run: |
          pytest -q

      - name: Build wheel
        run: |
          python -m pip install build
          python -m build --wheel --no-isolation
